apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: {{ .Values.global.namespace }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://user-service-db:5432/user_service_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
